In [ ]:
import numpy as np

In [ ]:
oneD_array = np.arange(9)
oneD_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Swapping first and second element
oneD_array[0], oneD_array[1] = oneD_array[1], oneD_array[0]
oneD_array

array([1, 0, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Swapping last and second last element
oneD_array[-1], oneD_array[-2] = oneD_array[-2], oneD_array[-1]
oneD_array

array([1, 0, 2, 3, 4, 5, 6, 8, 7])

In [ ]:
# Cleaning - Remove all odd elements
even_array = oneD_array[oneD_array % 2 == 0]
even_array

array([0, 2, 4, 6, 8])

In [ ]:
# For example, what if negative numbers meant invalid data.  Let's add a negative value
oneD_array[4] = -1
oneD_array

array([ 1,  0,  2,  3, -1,  5,  6,  8,  7])

In [ ]:
no_negative_array = oneD_array[oneD_array >=0]
no_negative_array

array([1, 0, 2, 3, 5, 6, 8, 7])

In [ ]:
twoD_array = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
twoD_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
# Swap 3rd and 4th row
twoD_array[[3,4],:] = twoD_array[[4,3],:]
twoD_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20],
       [13, 14, 15, 16]])

In [ ]:
# Swapping 1st and 3rd column
twoD_array[:, [2, 0]] = twoD_array[:, [0, 2]]
twoD_array

array([[ 3,  2,  1,  4],
       [ 7,  6,  5,  8],
       [11, 10,  9, 12],
       [19, 18, 17, 20],
       [15, 14, 13, 16]])