In [ ]:
import numpy as np

In [ ]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Slicing - array[start:end]
array[1:4]

array([1, 2, 3])

In [ ]:
# We can also define the step, like this: [start:end:step]
array[:8:2]

array([0, 2, 4, 6])

In [ ]:
# Reverse array
array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# To actually reverse it you'd need to do array = array[::-1] but let's restore it back from where it started

In [ ]:
array[::-1][2:6]

array([7, 6, 5, 4])

In [ ]:
array[array<3]

array([0, 1, 2])

In [ ]:
array[array>10]

array([], dtype=int64)

In [ ]:
# From prev. section
# Creating 2D arrays from python list
twoD_array = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
twoD_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Accessing individual element
twoD_array[0,2]

3

In [ ]:
# Slicing rows from 2 D array
twoD_array[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# All rows and 2nd,3rd column
twoD_array[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])