In [ ]:
import numpy as np

In [ ]:
array = np.arange(9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Reshape doesn't change the original array
array.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Resize directly changes the original array
array.resize(3, 3)

In [ ]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
twoD_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
twoD_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
np.transpose(twoD_array)

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [ ]:
array = np.arange(9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
plus_10_array = array + 10
plus_10_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
multiplied_by_2_array = array * 2
multiplied_by_2_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
plus_10_array.resize(3,3)
multiplied_by_2_array.resize(3,3)

In [ ]:
plus_10_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
multiplied_by_2_array

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
# Matrix Addition
plus_10_array + multiplied_by_2_array

array([[10, 13, 16],
       [19, 22, 25],
       [28, 31, 34]])

In [ ]:
array2 = np.arange(12)
array2.resize(3,4)
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
array3 = np.arange(12)
array3.resize(4,3)
array3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# Matrix multiplication array2 - (3,4) X array3 - (4,3)
ans = np.matmul(array2, array3)
ans

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])