In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([3,6,9])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
b

array([3, 6, 9])

In [ ]:
b.shape

(3,)

In [ ]:
# can we add a and b?  This will be done via broadcasting.  b will be
# replicated to match the desired dimension
a+b

array([[ 4,  8, 12],
       [ 7, 11, 15]])

In [ ]:
# behind the scenes, b gets broadcasted into an array like this below
b_broadcasted = np.array([[3,6,9], [3,6,9]])
b_broadcasted

array([[3, 6, 9],
       [3, 6, 9]])

In [ ]:
a+b_broadcasted

array([[ 4,  8, 12],
       [ 7, 11, 15]])

Let's try broadcasting in another dimension

In [ ]:
c = np.array([[3],[6]])
c

array([[3],
       [6]])

In [ ]:
c.shape

(2, 1)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a+c

array([[ 4,  5,  6],
       [10, 11, 12]])

Let's do an example of broadcasting for both arrays

In [ ]:
x = np.array([ [10,20,30] ])
x

array([[10, 20, 30]])

In [ ]:
x.shape

(1, 3)

In [ ]:
y = np.array([ [2], [4], [6] ])
y

array([[2],
       [4],
       [6]])

In [ ]:
y.shape

(3, 1)

In [ ]:
# if we add these, we'll get a 3x3 matrix.  Specifically, for the number of
# rows, we'll get the greater between 1 and 3 (so 3) and for the number of
# columns, we'll get the greater between 3 and 1 (so 3).  So both arrays
# will be broadcasted
x+y

array([[12, 22, 32],
       [14, 24, 34],
       [16, 26, 36]])

In [ ]:
# you can think of x as being turned into a 3x3 matrix like this
x_b = np.array([ [10,20,30], [10,20,30], [10,20,30] ])
x_b

array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]])

In [ ]:
# and y as a 3x3 matrix like this
y_b = np.array([ [2,2,2], [4,4,4], [6,6,6] ] )
y_b

array([[2, 2, 2],
       [4, 4, 4],
       [6, 6, 6]])

In [ ]:
# so we get the same result as above
x_b+y_b

array([[12, 22, 32],
       [14, 24, 34],
       [16, 26, 36]])

For more details on broadcasting rules, see:
https://numpy.org/doc/stable/user/basics.broadcasting.html

An example usecase from data analysis related to Neural Networks (if curious)

In [ ]:
# Neural Network usecase for broadcasting
# Calculating inputs for neural network -> W*X + B

weights = np.array([3.0, 2.0, 4.0])
X = np.array([4.0, 1.0, 3.0])
bias = 5.0

In [ ]:
weights*X + bias

array([17.,  7., 17.])