In [ ]:
import numpy as np

Create a 1D array

In [ ]:
array = np.arange(6)
array

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Random array - The function returns a numpy array with the specified shape filled with random float values between 0 and 1.
random_array = np.random.rand(10)
random_array

array([0.88632652, 0.91709473, 0.83444002, 0.04737235, 0.45267948,
       0.25633603, 0.3612494 , 0.2618606 , 0.56790836, 0.64282501])

In [ ]:
# Convert Python list to numpy array
list_a = [1, 2, 3]
a = np.array(list_a)
a

array([1, 2, 3])

In [ ]:
# Creating array filled with zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
# Number of elements in the array
len(array)

6

In [ ]:
# The length of one array element in bytes
array.itemsize

8

In [ ]:
complex_array = np.array([1, 2, 3, 4],  dtype = np.complex128)
complex_array.itemsize

16

In [ ]:
# 1st element from numpy array (0th index)
random_array[0]

0.8863265224069716

In [ ]:
# Convert numpy array to python list
random_array.tolist()

[0.8863265224069716,
 0.9170947349498932,
 0.8344400182943148,
 0.0473723482520888,
 0.45267948436914585,
 0.2563360274471497,
 0.36124939929450606,
 0.26186060367170205,
 0.5679083604156187,
 0.6428250128220807]

Create a 2D array

In [ ]:
# Creating 2D arrays from python list
twoD_array = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
twoD_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Number of dimensions
twoD_array.ndim

2

In [ ]:
# Individual dimensions
twoD_array.shape

(3, 4)

In [ ]:
# 2D indexing - Accessing element from Row 2 and Column 3
twoD_array[1][2]

7